export const temporaryNews = [
  {
    key: 1,
    name: "Google",
    anons: "Google!!!",
    full: "Google is coll!",
    img: "https://cdn1.iconfinder.com/data/icons/google-s-logo/150/Google_Icons-09-512.png",
  },
  {
    key: 2,
    name: "Apple",
    anons: "Apple!!!",
    full: "Apple is coll!",
    img: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Apple-logo.png",
  },
  {
    key: 3,
    name: "FaceBook",
    anons: "FaceBook!!!",
    full: "FaceBook is coll!",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Facebook_Logo_%282019%29.png/1024px-Facebook_Logo_%282019%29.png",
  },
  {
    key: 4,
    name: "Google",
    anons: "Google!!!",
    full: "Google is coll!",
    img: "https://cdn1.iconfinder.com/data/icons/google-s-logo/150/Google_Icons-09-512.png",
  },
  {
    key: 5,
    name: "Apple",
    anons: "Apple!!!",
    full: "Apple is coll!",
    img: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Apple-logo.png",
  },
  {
    key: 6,
    name: "FaceBook",
    anons: "FaceBook!!!",
    full: "FaceBook is coll!",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Facebook_Logo_%282019%29.png/1024px-Facebook_Logo_%282019%29.png",
  },
  {
    key: 7,
    name: "Google",
    anons: "Google!!!",
    full: "Google is coll!",
    img: "https://cdn1.iconfinder.com/data/icons/google-s-logo/150/Google_Icons-09-512.png",
  },
  {
    key: 8,
    name: "Apple",
    anons: "Apple!!!",
    full: "Apple is coll!",
    img: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Apple-logo.png",
  },
  {
    key: 9,
    name: "FaceBook",
    anons: "FaceBook!!!",
    full: "FaceBook is coll!",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Facebook_Logo_%282019%29.png/1024px-Facebook_Logo_%282019%29.png",
  },
  {
    key: 10,
    name: "Google",
    anons: "Google!!!",
    full: "Google is coll!",
    img: "https://cdn1.iconfinder.com/data/icons/google-s-logo/150/Google_Icons-09-512.png",
  },
  {
    key: 11,
    name: "Apple",
    anons: "Apple!!!",
    full: "Apple is coll!",
    img: "https://upload.wikimedia.org/wikipedia/commons/a/ab/Apple-logo.png",
  },
  {
    key: 12,
    name: "FaceBook",
    anons: "FaceBook!!!",
    full: "FaceBook is coll!",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/0/05/Facebook_Logo_%282019%29.png/1024px-Facebook_Logo_%282019%29.png",
  },
];

export default temporaryNews;
